### ISSUE TITLE
Question: Is AF3 temporarily not supported for input involving glycosylation modifications?

### ISSUE THREAD

**Issue by XIANZHE-LI** [google-deepmind/alphafold3#216] opened 2024-12-17 04:27 UTC
For “Glycans
If the JSON in alphafoldserver format specifies glycans, the converter will raise an error. This is because translating glycans specified in the alphafoldserver format to the alphafold3 format is not currently supported.”
I am not certain if I have misunderstood, but is it the case that AF3 does not currently support the input of glycosylation modifications?

This is my JSON.

```json
{
  "name": "CREB3_231-371_TMD-CTD_homotrimer_307&348_NAG",
  "sequences": [
    {
      "protein": {
        "id": ["A"],
        "sequence": "ILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEWPFPDLFSEPLCRGPILPLQANLTRKGGWLPTGSPSVILQDRYSG",
"modifications": [
      {"ptmType": "NAG", "ptmPosition": 77} ,   
 {"ptmType": "NAG", "ptmPosition": 118}
]
      }
    },
{"protein": {
        "id": ["B"],
        "sequence": "ILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEWPFPDLFSEPLCRGPILPLQANLTRKGGWLPTGSPSVILQDRYSG",
"modifications": [
      {"ptmType": "NAG", "ptmPosition": 77} ,   
 {"ptmType": "NAG", "ptmPosition": 118}
]
      }
    },

{"protein": {
        "id": ["C"],
        "sequence": "ILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEWPFPDLFSEPLCRGPILPLQANLTRKGGWLPTGSPSVILQDRYSG",
"modifications": [
      {"ptmType": "NAG", "ptmPosition": 77} ,   
 {"ptmType": "NAG", "ptmPosition": 118}
]

      }
    }
  ],
  "modelSeeds": [1234678910],
  "dialect": "alphafold3",
  "version": 1
}
```

```
Traceback (most recent call last):
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/root/lanyun-tmp/AF3/alphafold3/run_alphafold.py", line 362, in predict_structure
    featurised_examples = featurisation.featurise_input(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/alphafold3/data/featurisation.py", line 76, in featurise_input
    batch = data_pipeline.process_item(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/alphafold3/model/pipeline/pipeline.py", line 318, in process_item
    batch_msa = features.MSA.compute_features(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/alphafold3/model/features.py", line 483, in compute_features
    unpaired_msa = msa_module.Msa.from_a3m(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/alphafold3/data/msa.py", line 220, in from_a3m
    return cls(
           ^^^^
  File "/root/miniconda/envs/af3-2/lib/python3.11/site-packages/alphafold3/data/msa.py", line 108, in __init__
    raise ValueError(
ValueError: First MSA sequence ILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGNTSCLLHYMPQAPSAEPPLEWPFPDLFSEPLCRGPILPLQANLTRKGGWLPTGSPSVILQDRYSG is not the query_sequence='ILVLLVSFCLLLVPAMYSSDTRGSLPAEHGVLSRQLRALPSEDPYQLELPALQSEVPKDSTHQWLDGSDCVLQAPGXTSCLLHYMPQAPSAEPPLEWPFPDLFSEPLCRGPILPLQAXLTRKGGWLPTGSPSVILQDRYSG'
```

**Comment by Augustin-Zidek** [comment] 2024-12-17 10:15
This is a duplicate of https://github.com/google-deepmind/alphafold3/issues/54 and https://github.com/google-deepmind/alphafold3/issues/132.

I have fixed this issue in https://github.com/google-deepmind/alphafold3/commit/44dee65fb265461bc743b5a079d990181e7738ee.

Please clone the latest commit and rebuild your AlphaFold 3 container to get the fix.

**Closed by Augustin-Zidek** 2024-12-17 10:15 UTC
Labels: bug, duplicate
