### ISSUE TITLE
docker run error:  Importing the numpy C-extensions failed.

### ISSUE THREAD

**Issue by carrisonj** [google-deepmind/alphafold3#93] opened 2024-11-21 09:30 UTC
docker run cli as follow:
docker run -it     --volume $HOME/af_input:/root/af_input     --volume $HOME/af_output:/root/af_output     --volume $MODEL_PARAMETERS_DIR:/root/models     --volume $DB_DIR:/root/public_databases     --gpus all  alphafold3    python3 run_alphafold.py     --json_path=/root/af_input/fold_input.json     --model_dir=/root/models     --output_dir=/root/af_output

i've add lines below to run_alphafold.py, 
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
before
import numpy as np

still got same error. pls help me, thx a lot.

**Comment by Augustin-Zidek** [comment] 2024-11-21 09:45
This is a duplicate of https://github.com/google-deepmind/alphafold3/issues/83, let's continue the discussion there.

**Closed by Augustin-Zidek** 2024-11-21 09:45 UTC
Labels: duplicate
