### ISSUE TITLE
Run templates does not work with external MSA

### ISSUE THREAD

**Issue by sky1ove** [google-deepmind/alphafold3#169] opened 2024-12-03 21:01 UTC
External MSA pipeline such as mmseq2 works fine without running template, but if try to run the template search (by setting templates to null in the input json), it shows error:

```
Found local devices: [CudaDevice(id=0)]
Building model from scratch...
Processing fold inputs.
Processing fold input #1
Processing fold input PDCD1_CEACAM3
Checking we can load the model parameters...
Running data pipeline...
Processing chain A
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/hmmer/bin/hmmbuild', '--informat', 'stockholm', '--hand', '--amino', '/tmp/tmpg1kj0lvf/output.hmm', '/tmp/tmpg1kj0lvf/query.msa']' returned non-zero exit status 7.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 737, in <module>
    app.run(main)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/alphafold3_venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/alphafold/run_alphafold.py", line 721, in main
    process_fold_input(
  File "/app/alphafold/run_alphafold.py", line 567, in process_fold_input
    fold_input = pipeline.DataPipeline(data_pipeline_config).process(fold_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 527, in process
    processed_chains.append(self.process_protein_chain(chain))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 444, in process_protein_chain
    template_hits = _get_protein_templates(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/pipeline.py", line 41, in _get_protein_templates
    protein_templates = templates_lib.Templates.from_seq_and_a3m(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/templates.py", line 469, in from_seq_and_a3m
    hmmsearch_a3m = run_hmmsearch_with_a3m(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/templates.py", line 970, in run_hmmsearch_with_a3m
    return searcher.query_with_sto(sto, model_construction='hand')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/hmmsearch.py", line 146, in query_with_sto
    hmm = self.hmmbuild_runner.build_profile_from_sto(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/hmmbuild.py", line 64, in build_profile_from_sto
    return self._build_profile(
           ^^^^^^^^^^^^^^^^^^^^
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/hmmbuild.py", line 133, in _build_profile
    subprocess_utils.run(
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/data/tools/subprocess_utils.py", line 94, in run
    raise RuntimeError(error_msg) from e
RuntimeError: Hmmbuild failed
stdout:
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.4 (Aug 2023); http://hmmer.org/
# Copyright (C) 2023 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             /tmp/tmpg1kj0lvf/query.msa
# output HMM file:                  /tmp/tmpg1kj0lvf/output.hmm
# input alignment is asserted as:   protein
# model architecture construction:  hand-specified by RF annotation
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
```

I tried the AF3 default unpaired MSA with templates set to null, it runs templates search successfully.
Here's a screen shot for default unpaired MSA that works for template search
![image](https://github.com/user-attachments/assets/1025426f-af57-4a18-b66e-25d381201e95)

And Here's a screenshot for mmseq2 MSA that does not work for template search
![image](https://github.com/user-attachments/assets/801b6e84-ce33-4eb4-b1e4-678492c7e5bf)
However, if skip template search, it works fine.

Not sure if template search hmmbuild has to do with the a2m format.

Input files are attached. 
[mmseq2MSA_run_template.json](https://github.com/user-attachments/files/17999193/mmseq2MSA_run_template.json)
[afMSA_run_template.json](https://github.com/user-attachments/files/17999194/afMSA_run_template.json)

**Comment by Augustin-Zidek** [comment] 2024-12-04 16:37
Hey, sorry, this is a bug -- I've missed this in https://github.com/google-deepmind/alphafold3/commit/cdbcf41b71235ec33338edef1f80e03fb0c6bae4. The problem is that the a3m has lowercase characters -- these need to be removed before running Hmmalign.

I will send a fix shortly. The workaround in the meanwhile is to modify the a3m so that it doesn't contain any lowercase letters in the sequences.

**Comment by Augustin-Zidek** [comment] 2024-12-04 17:22
I can't reproduce it with the MMSeqs2 a3m you have provided. Could you include the `stderr` output from Hmmbuild? Is it also possible your input is somewhat corrupted?

**Comment by sky1ove** [comment] 2024-12-04 17:30
[PDCD1.a3m.zip](https://github.com/user-attachments/files/18012042/PDCD1.a3m.zip)
[IL1RL1.a3m.zip](https://github.com/user-attachments/files/18012044/IL1RL1.a3m.zip)
attached are two a3m files from mmseq2. Could you try with this? (first line is the original sequence)

I'll see if I can get the hmmbuild stderr output.

**Comment by Augustin-Zidek** [comment] 2024-12-04 17:30
I actually just managed to reproduce -- the problem is with the TAB (`\t`) characters in the sequence descriptions. If you do `.replace('\t', ' ')` on the MMSeqs2 MSA, it fixes the issue. I will add a fix for this in our code.

**Comment by sky1ove** [comment] 2024-12-04 17:32
ok thanks. 

I just pull the latest git and rebuilt the docker image, it seems there's a import issue

```
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 52, in <module>
    from alphafold3.model.diffusion import model as diffusion_model
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/model.py", line 29, in <module>
    from alphafold3.model.diffusion import atom_cross_attention
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/atom_cross_attention.py", line 19, in <module>
    from alphafold3.model.diffusion import diffusion_transformer
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/model/diffusion/diffusion_transformer.py", line 14, in <module>
    from alphafold3.jax.gated_linear_unit import gated_linear_unit
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/jax/gated_linear_unit/gated_linear_unit.py", line 20, in <module>
    from alphafold3.jax.gated_linear_unit import matmul_ext
  File "/alphafold3_venv/lib/python3.11/site-packages/alphafold3/jax/gated_linear_unit/matmul_ext.py", line 24, in <module>
    from jax.experimental.pallas import triton as plgpu
ImportError: cannot import name 'triton' from 'jax.experimental.pallas' (/alphafold3_venv/lib/python3.11/site-packages/jax/experimental/pallas/__init__.py)
```

**Comment by Augustin-Zidek** [comment] 2024-12-04 17:36
Sorry, we pushed a breaking commit: https://github.com/google-deepmind/alphafold3/commit/24a8257a0aa2c67cb51f2b1c9177779d2bd4e3c4

Please sync to code before that.

**Comment by sky1ove** [comment] 2024-12-04 17:37
sure. thanks!

**Comment by Augustin-Zidek** [comment] 2024-12-04 19:11
The problematic commit has been rolled back in https://github.com/google-deepmind/alphafold3/commit/b7e8c85ad97f2eeb9c4b6af7d1dd1960031e353d.

The fix for the tabs issue in sequence descriptions was fixed in a follow-up commit https://github.com/google-deepmind/alphafold3/commit/26e3bf3a261bb5b3983a478bcbb8f2c895daf946.

Thanks for reporting.

**Closed by Augustin-Zidek** 2024-12-04 19:11 UTC
Labels: bug
