### ISSUE TITLE
Guidance on Predicting Protein-Peptide Complexes Using AlphaFold3

### ISSUE THREAD

**Issue by ACIITB23** [google-deepmind/alphafold3#135] opened 2024-11-27 17:47 UTC
I am currently facing an issue with predicting protein-peptide complexes. I have successfully installed AlphaFold3 locally and received the model parameters. While I am able to predict individual protein structures using the appropriate commands, I am encountering difficulties when trying to predict complexes. I have tried modifying the JSON files, but I was unable to run the predictions successfully.

Could you kindly provide the steps and commands required for predicting protein-peptide complexes? Additionally, I would appreciate guidance on how to handle predictions for more than 100 sequences.

Thank you very much for your assistance!

**Comment by zhanglzu** [comment] 2024-11-28 01:31
This is a JSON file for predicting protein complexes that I used. Maybe it was  correctly.For reference only.

{
    "name": "pos_v4",
    "modelSeeds": [
        10,
        42
    ],
    "sequences": [
        {
            "protein": {
                "id": "E",
                "sequence": "MSSTHSNNVGHPQSSPQGPLTEQQRAQQQYQIFENSLPKVSQSVYQMLLNEMVPLAMGIERQISGDVISSDSNVTSENGNINNMIKRLKIEEHHTVDIIRSHNLIHELYKADEEEKEKVLARLRNIGFQIGLKLSELLIFSNNPNLKFKEMDLLLIMKFICRDVWKQIFGKQIDNLKTNHRGTFYLLDYDYRPIQSFSLEEDAKNEELKMIEPFLEIPVGIIRGVLSSLGYSSEEVICLASFIDRPTDRPKTAFPKGVSFHVQVTMPQ"
            }
        },
        {
            "protein": {
                "id": "P",
                "sequence": "MVSTTQSRSLKAMGEEIWKNKTEKINTELFTLTYGSIVAQLCQDYERDFNKVNDHLYSMGYNIGCRLIEDFLARTALPRCENLVKTSEVLSKCAFKIFLNITPNITNWSHNKDTFSLILDENPLADFVELPMDAMKSLWYSNILCGVLKGSLEMVQLDCDVWFVSDILRGDSQTEIKVKLNRILKDEIPIGED"
            }
        }
    ],
    "dialect": "alphafold3",
    "version": 1
}

**Comment by Augustin-Zidek** [comment] 2024-11-28 10:25
Agreed with the comment above -- specify your two chains using the AlphaFold 3 JSON format and pass path of the input JSON file as a flag to AlphaFold. Refer also to https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md for more details.

> Additionally, I would appreciate guidance on how to handle predictions for more than 100 sequences.

Specify the 100+ sequences in the `sequences` field. In case some have multiple copies, you can specify them just once and use the multi-id functionality: `"id": ["A", "B", "C", ...]`.

**Comment by ACIITB23** [comment] 2024-12-02 17:20
Thank you for the response. @zhanglzu @Augustin-Zidek 
I used the above examples and suggestions, and they are working fine.

**Comment by ACIITB23** [comment] 2024-12-06 18:29
Hi @zhanglzu @Augustin-Zidek ,

I prepared 100 JSON files containing protein and peptide sequence information, following the specified format. When I use a single JSON file with the option `--json_path=file.json`, it runs successfully. However, when I specify a folder containing all JSON files using` --input_dir=JSONfile_folderpath/`, I encounter an error stating that 'JSON is not an AlphaFold3 JSON since the top level is not a list.' How can I resolve this issue?

Please help me resolve this issue; it might be that I am not giving a specific file format.

**Comment by Augustin-Zidek** [comment] 2024-12-06 19:29
Could you post the full stack trace with the error?

**Comment by ACIITB23** [comment] 2024-12-06 19:39
```
Command using for a single file:
singularity exec --nv alphafold3.sif python run_alphafold.py --json_path=FLP.json --model_dir=/home/achaudh6/Documents/AF3work/Alphafold3/ --db_dir=public_databases/ --output_dir=Out/

Command using for multiple JSON files:
singularity exec --nv alphafold3.sif python run_alphafold.py --input_dir=JSONfolder/  --model_dir=/home/achaudh6/Documents/AF3work/Alphafold3/ --db_dir=public_databases/ --output_dir=Out/
```
See the screenshot of the error when I am using for multiple JSON files:
![Screenshot from ](https://github.com/user-attachments/assets/8df9807e-28d3-4df9-a78c-1c9eeed87fc3)

**Comment by Augustin-Zidek** [comment] 2024-12-06 19:45
Ah, right, these are just information messages (note the leading `I` on the left), so it is ok to ignore these -- everything is working as intended.

**Comment by ACIITB23** [comment] 2024-12-06 20:09
Am I using the correct command for processing multiple files? 

After displaying the information message, nothing happens, and it returns to the home prompt.

What should I do? Could you please suggest a way to run multiple JSON files?"

**Comment by ACIITB23** [comment] 2024-12-06 20:34
![Screenshot from 2024-12-06 14-33-09ff](https://github.com/user-attachments/assets/7fcd6c0a-b336-4961-8cc1-7daabf19d16e)
I tried again and found these printed names just below these JSON is not an AlphaFold3 JSON since the top level is not a list. 

What could be the reason?

**Comment by ACIITB23** [comment] 2024-12-13 18:37
Hi @Augustin-Zidek @zhanglzu 

Could you please help to resolve the above issues?

**Comment by Augustin-Zidek** [comment] 2024-12-13 18:41
Ah, I think I know what the issue is. Are all of the names of your inputs unique? 

You have two options how to solve this. Either make them all unique (as the error likely says), or upgrade AlphaFold past https://github.com/google-deepmind/alphafold3/commit/223c4c61d452022a1b8c8fe327afda8490b96419 where we removed this check since it is no longer needed.

**Comment by ACIITB23** [comment] 2024-12-13 21:09
@Augustin-Zidek 
Thank you for your prompt response. 

Yes, All file names are unique.

Before, I was trying with 1000 files in a folder; I created and tried with only 100 files. It's working.

`singularity exec --nv alphafold3.sif python run_alphafold.py --input_dir=JSONfolder/  --model_dir=/home/achaudh6/Documents/AF3work/Alphafold3/ --db_dir=public_databases/ --output_dir=Out/
`


Still, I am wondering if it works with 100 files but not with thousands of files. What could be the reason behind this?
 
I saw some of the files have (Underscore -), (dash -), and small brackets ( ) in their file name. Does it matter?

How many files could we give as input? Are there any limitations?

**Comment by Augustin-Zidek** [comment] 2024-12-13 22:24
Hello @ACIITB23, the problem is not with the JSON file names, but rather with the `"name"` field in each of the JSON files -- each of these must be unique.

> How many files could we give as input? Are there any limitations?

The only limitation before https://github.com/google-deepmind/alphafold3/commit/aa724ca1cbfc7084fa683d27418a0d86d6228cd4 used to be how many can fit into RAM (which should be significantly more than 100 in MSA is not included), but after that commit there should not really be any limit.

**Comment by Augustin-Zidek** [comment] 2024-12-17 10:11
Did this resolve your issue? I also pushed a small improvement to make the logging less verbose and the error messages a bit clearer, see https://github.com/google-deepmind/alphafold3/commit/9befb639292fb53fa36b5a3e6ee0273e5a1d1094.

**Comment by ACIITB23** [comment] 2024-12-17 17:46
Hi @Augustin-Zidek 

Thank you for the help; I really appreciate the support. 
It is running now with the same files.

I am using the sbatch job script with the submission command `sbatch  --array=0-999 AF3jobsub.sh ` to take input for all files.

I will also try the last suggestion and let you know if anything comes up.

**Comment by Augustin-Zidek** [comment] 2024-12-17 17:58
Great, I will close this issue for now then, feel free to re-open, comment, or open a new issue if you hit any other problems.

**Closed by Augustin-Zidek** 2024-12-17 17:58 UTC
Labels: question

**Comment by jchenpku** [comment] 2024-12-20 04:20
I can run json file from @zhanglzu without problem, however I modified it a little bit then there is an error `ValueError: Failed to load fold input from /af_input/RTH258_VEGFA.json. The JSON at /af_input/RTH258_VEGFA.json was detected to be an AlphaFold 3 JSON since the top-level is not a list.`

my input is like this, thanks for any suggestions:
```
{
    "name": "RTH258_VEGFA",
    "modelSeeds": [
        10,
        42
    ],
    "sequences": [
        {
            "protein": {
                "id": "RTH258",
                "sequence": "EIVMTQSPSTLSASVGDRVIITCQASEIIHSWLAWYQQKPGKAPKLLIYLASTLASGVPSRFSGSGSGAEFTLTISSLQPDDFATYYCQNVYLASTNGANFGQGTKLTVLGGGGGSGGGGSGGGGSGGGGSEVQLVESGGGLVQPGGSLRLSCTASGFSLTDYYYMTWVRQAPGKGLEWVGFIDPDDDPYYATWAKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAGGDHNSGWGLDIWGQGTLVTVSSEF"
            }
        },
        {
            "protein": {
                "id": "VEGFA",
                "sequence": "MTDRQTDTAPSPSYHLLPGRRRTVDAAASRGQGPEPAPGGGVEGVGARGVALKLFVQLLGCSRFGGAVVRAGEAEPSGAARSASSGREEPQPEEGEEEEEKEEERGPQWRLGARKPGSWTGEAAVCADSAPAARAPQALARASGRGGRVARRGAEESGPPHSPSRRGSASRAGPGRASETMNFLLSWVHWSLALLLYLHHAKWSQAAPMAEGGGQNHHEVVKFMDVYQRSYCHPIETLVDIFQEYPDEIEYIFKPSCVPLMRCGGCCNDEGLECVPTEESNITMQIMRIKPHQGQHIGEMSFLQHNKCECRPKKDRARQEKKSVRGKGKGQKRKRKKSRYKSWSVPCGPCSERRKHLFVQDPQTCKCSCKNTDSRCKARQLELNERTCRCDKPRR"
            }
        }
    ],
    "dialect": "alphafold3",
    "version": 1
}
```

> This is a JSON file for predicting protein complexes that I used. Maybe it was not entirely correct. For reference only.
> 
> ```
> {
>     "name": "pos_v4",
>     "modelSeeds": [
>         10,
>         42
>     ],
>     "sequences": [
>         {
>             "protein": {
>                 "id": "E",
>                 "sequence": "MSSTHSNNVGHPQSSPQGPLTEQQRAQQQYQIFENSLPKVSQSVYQMLLNEMVPLAMGIERQISGDVISSDSNVTSENGNINNMIKRLKIEEHHTVDIIRSHNLIHELYKADEEEKEKVLARLRNIGFQIGLKLSELLIFSNNPNLKFKEMDLLLIMKFICRDVWKQIFGKQIDNLKTNHRGTFYLLDYDYRPIQSFSLEEDAKNEELKMIEPFLEIPVGIIRGVLSSLGYSSEEVICLASFIDRPTDRPKTAFPKGVSFHVQVTMPQ"
>             }
>         },
>         {
>             "protein": {
>                 "id": "P",
>                 "sequence": "MVSTTQSRSLKAMGEEIWKNKTEKINTELFTLTYGSIVAQLCQDYERDFNKVNDHLYSMGYNIGCRLIEDFLARTALPRCENLVKTSEVLSKCAFKIFLNITPNITNWSHNKDTFSLILDENPLADFVELPMDAMKSLWYSNILCGVLKGSLEMVQLDCDVWFVSDILRGDSQTEIKVKLNRILKDEIPIGED"
>             }
>         }
>     ],
>     "dialect": "alphafold3",
>     "version": 1
> }
> ```

**Comment by zhanglzu** [comment] 2024-12-20 09:13
@jchenpku It seems that the sequence ID in AF3 can only be ONE UPPER character.

**Comment by Augustin-Zidek** [comment] 2024-12-20 09:20
@jchenpku the sequence IDs can consist only of uppercase letters, so the problem is with the `RTH258` ID. Change it e.g. to `RTH` and you should be good to go. Note also that with more than single-letter chain IDs you won't get RASA calculation (MKDSSP requires chain IDs to be single-letter only).

I know this restriction is somewhat arbitrary, but it will need some changes deep in AlphaFold stack to get rid of that restriction. I am planning to fix that.

**Comment by jchenpku** [comment] 2024-12-20 09:31
thank you very much @Augustin-Zidek, I just also figured this out by inspecting the folding_input.py file. It might be really helpful to include this information in the documentation to assist others in the future.

**Comment by Augustin-Zidek** [comment] 2024-12-20 10:02
@jchenpku It is already included in the documentation:

https://github.com/google-deepmind/alphafold3/blob/main/docs/input.md#sequences

> `id: str | list[str]`: An **uppercase letter or multiple letters** specifying the unique IDs for each copy of this protein chain. The IDs are then also used in the output mmCIF file. Specifying a list of IDs (e.g. `["A", "B", "C"]`) implies a homomeric chain with multiple copies.

Also, there is a check that also gives a nice error message with an explanation (see https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/common/folding_input.py#L166) -- this was in the error above the `ValueError` you posted.

However, I will change the logic there to make the actual error more prominent in the `ValueError: Failed to load fold input from ...`.
