### ISSUE TITLE
First MSA sequence is not the {query_sequence=}'

### ISSUE THREAD

**Issue by James-lin9** [google-deepmind/alphafold3#132] opened 2024-11-27 06:57 UTC
Hi, I ran default MSA search by jackhammer for P26341 (uniprot ID)  and then when I did the inference, I got an error: 'First MSA sequence is not the {query_sequence=}'. How do I fix this? Shall I rerun the jackhammer? 
I check the run_alphafold.py this could be caused by mutation from jackhammer?
"# Check if the 1st MSA sequence matches the query sequence. Since it may be mutated by the search tool (jackhmmer) check using the featurized version."

**Comment by Augustin-Zidek** [comment] 2024-11-29 16:55
Hello, thank you for reporting. Do you have any pTMs in your sequence? If so, this is a duplicate of https://github.com/google-deepmind/alphafold3/issues/54 and we are working on a fix.

**Comment by James-lin9** [comment] 2024-11-30 13:43
> Hello, thank you for reporting. Do you have any pTMs in your sequence? If so, this is a duplicate of #54 and we are working on a fix.

No. The modification is empty in the input json. I found that somehow U is mutated to X in the run_inference step while the data_pipeline output looks fine. It seems a bug in the run inference step even without modifications.
In addition, I found 2 more proteins: O60613 and P07203 got the same error. Not sure if the error can be reproduced or not.

**Comment by Augustin-Zidek** [comment] 2024-12-03 16:57
Right, thanks! I will send a fix for this. 

In the meanwhile, the workaround is to change all `U` residues to `X` in the input (same for `B`, `J`, `O`, `U`, `Z`).

**Comment by Augustin-Zidek** [comment] 2024-12-17 10:14
This has been fixed in https://github.com/google-deepmind/alphafold3/commit/44dee65fb265461bc743b5a079d990181e7738ee, sorry for the delay!

Please clone the latest commit and rebuild your AlphaFold 3 container to get the fix.

**Closed by Augustin-Zidek** 2024-12-17 10:14 UTC
Labels: bug
