### ISSUE TITLE
Error occurred when modeling post-translational modification

### ISSUE THREAD

**Issue by hqdream** [google-deepmind/alphafold3#192] opened 2024-12-08 04:27 UTC
Great thanks for providing AF3.

I encountered a error when modeling post-translational modification. I used the following Json file as input to predict the structure of a protein with lactylation modification at the lysine (K13):

{
    "name": "histone_LAC",
    "modelSeeds": [1],
    "sequences": [
        {
            "protein": {
                "id": "A",
                "sequence": "MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG",
                "modifications": [
                {
                "ptmType": "2OP", "ptmPosition": 13
                }
                ]
            }
        }
    ],
    "dialect": "alphafold3",
    "version": 1
}

However, the following error occurred: 

ValueError: First MSA sequence MSGRGKGGKGLGKGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG is not the query_sequence='MSGRGKGGKGLGXGGAKRHRKVLRDNIQGITKPAIRRLARRGGVKRISGLIYEETRGVLKVFLENVIRDAVTYTEHAKRKTVTAMDVVYALKRQGRTLYGFGG'

Could anyone help me out?

Many thanks!

**Comment by joshabramson** [comment] 2024-12-08 12:16
This looks like a duplicate of https://github.com/google-deepmind/alphafold3/issues/54 - we are working on a fix.

**Closed by joshabramson** 2024-12-08 12:16 UTC
Labels: duplicate
